### PR TITLE
Closes #47 [disable scroll when popup opened]

### LINKED ISSUE #47: Disable scroll when popup opened

### PR DESCRIPTION
**Pull request by CodeModeYT**
Warum sind da jetzt so viele changes?! 😂

### CODE REVIEW

**Review by Mr-Comand — CHANGES_REQUESTED** [review]
grafik

**Comment by Mr-Comand** [comment]
i think there is a mixup between the issues ids

**Comment by CodeModeYT** [comment]
> grafik
> 
> 

Die PR is eigentlich auch für nen anderen issue, da sind iwi zu viele files mit drin. 
Die sollte eigentlich nur für disable scroll when popup opened sein

**Comment by Mr-Comand** [comment]
please also finish fixing #31 as we can merge it.

**Review by Mr-Comand — CHANGES_REQUESTED** [review]
it is possible that the table does not jump when opening the popup(because the scroll bar disappears)

**Comment by CodeModeYT** [comment]
> it is possible that the table does not jump when opening the popup(because the scroll bar disappears)

?
(Warum sollte die table jumpen?)

**Comment by Mr-Comand** [comment]
> > it is possible that the table does not jump when opening the popup(because the scroll bar disappears)
> 
> ? (Warum sollte die table ju

https://github.com/user-attachments/assets/23a81ae3-1cb1-4d77-b1ce-547fe45b1517

mpen?)

**Review by Mr-Comand — APPROVED** [review]
LGTM

**Pull request merged**
